// The same registry drives validated API resources, navigation, forms and feature switches.
export const roles = {
  admin: 'مدیر مدرسه',
  teacher: 'معلم',
  student: 'دانش‌آموز',
  parent: 'ولی دانش‌آموز',
};
const opts = (...items) => items.map(([value, label]) => ({ value, label }));
const field = (name, label, type = 'text', extra = {}) => ({ name, label, type, ...extra });
const ref = (name, label, resource, extra = {}) =>
  field(name, label, 'reference', { resource, ...extra });
const num = (name, label, extra = {}) =>
  field(name, label, 'number', {
    min: 0,
    ...(label.includes('تومان') ? { integer: true } : {}),
    ...extra,
  });
const date = (name, label, extra = {}) => field(name, label, 'date', extra);
const select = (name, label, options, extra = {}) =>
  field(name, label, 'select', { options, ...extra });
const required = { required: true };
const everyone = ['admin', 'teacher', 'student', 'parent'];
const educators = ['admin', 'teacher'];
const gradeOptions = opts(
  ['1', 'اول'],
  ['2', 'دوم'],
  ['3', 'سوم'],
  ['4', 'چهارم'],
  ['5', 'پنجم'],
  ['6', 'ششم'],
  ['7', 'هفتم'],
  ['8', 'هشتم'],
  ['9', 'نهم'],
  ['10', 'دهم'],
  ['11', 'یازدهم'],
  ['12', 'دوازدهم'],
);
export const moduleDefs = [
  {
    id: 'dashboard',
    name: 'داشبورد',
    description: 'نمای کلی مدرسه، آمار و فعالیت‌های روزانه',
    icon: 'LayoutDashboard',
    color: 'purple',
  },
  {
    id: 'students',
    name: 'دانش‌آموزان',
    description: 'پرونده، اولیا، سلامت و سوابق دانش‌آموز',
    icon: 'GraduationCap',
    color: 'blue',
  },
  {
    id: 'teachers',
    name: 'معلمان و کارکنان',
    description: 'مدیریت همکاران، حساب کاربری و حقوق',
    icon: 'UsersRound',
    color: 'orange',
  },
  {
    id: 'classes',
    name: 'کلاس‌ها و فضاها',
    description: 'کلاس‌بندی، معلم راهنما و مدیریت اتاق‌ها',
    icon: 'School',
    color: 'green',
  },
  {
    id: 'attendance',
    name: 'حضور و غیاب',
    description: 'ثبت روزانه، تأخیر، غیبت و گزارش کلاس',
    icon: 'CalendarCheck2',
    color: 'purple',
  },
  {
    id: 'education',
    name: 'آموزش و نمرات',
    description: 'دروس، برنامه هفتگی، تکالیف و ارزشیابی',
    icon: 'BookOpen',
    color: 'blue',
  },
  {
    id: 'tickets',
    name: 'پیام‌ها و تیکت‌ها',
    description: 'ارتباط امن با مدیر و معلمان و پیوست فایل',
    icon: 'MessagesSquare',
    color: 'pink',
  },
  {
    id: 'announcements',
    name: 'اطلاعیه‌ها',
    description: 'اطلاع‌رسانی هدفمند به اعضای مدرسه',
    icon: 'Megaphone',
    color: 'orange',
  },
  {
    id: 'calendar',
    name: 'تقویم و رویدادها',
    description: 'جلسات، اردوها، مناسبت‌ها و برنامه‌ها',
    icon: 'CalendarDays',
    color: 'green',
  },
  {
    id: 'finance',
    name: 'امور مالی',
    description: 'شهریه، رسید پرداخت و هزینه‌های مدرسه',
    icon: 'Wallet',
    color: 'purple',
  },
  {
    id: 'library',
    name: 'کتابخانه',
    description: 'کتاب‌ها، موجودی و گردش امانت',
    icon: 'Library',
    color: 'blue',
  },
  {
    id: 'services',
    name: 'خدمات مدرسه',
    description: 'سرویس، تجهیزات و ثبت ورود مهمانان',
    icon: 'Boxes',
    color: 'orange',
  },
  {
    id: 'reports',
    name: 'گزارش‌ها',
    description: 'تحلیل آموزشی، حضور و مالی با خروجی CSV',
    icon: 'ChartNoAxesCombined',
    color: 'green',
  },
  {
    id: 'notifications',
    name: 'اعلان‌ها',
    description: 'صندوق اعلان و وضعیت خوانده‌شدن',
    icon: 'Bell',
    color: 'pink',
  },
  {
    id: 'profile',
    name: 'حساب کاربری',
    description: 'ویرایش مشخصات و تغییر امن رمز عبور',
    icon: 'CircleUserRound',
    color: 'blue',
  },
  {
    id: 'settings',
    name: 'تنظیمات سامانه',
    description: 'مدرسه، سال تحصیلی، کاربران و پشتیبان',
    icon: 'Settings2',
    color: 'purple',
    locked: true,
  },
];
export const resourceDefs = {
  students: {
    module: 'students',
    title: 'دانش‌آموزان',
    singular: 'دانش‌آموز',
    icon: 'GraduationCap',
    read: everyone,
    write: ['admin'],
    display: ['first_name', 'last_name'],
    columns: ['first_name', 'class_id', 'guardian_name', 'guardian_phone', 'status'],
    fields: [
      field('first_name', 'نام', 'text', required),
      field('last_name', 'نام خانوادگی', 'text', required),
      field('national_id', 'کد ملی', 'text', { pattern: 'national', unique: true }),
      ref('class_id', 'کلاس', 'classes', required),
      date('birth_date', 'تاریخ تولد'),
      select('gender', 'جنسیت', opts(['male', 'پسر'], ['female', 'دختر']), { default: 'male' }),
      field('phone', 'شماره تماس', 'tel'),
      field('email', 'ایمیل', 'email'),
      field('guardian_name', 'نام ولی', 'text', required),
      field('guardian_phone', 'شماره تماس ولی', 'tel', required),
      select(
        'guardian_relation',
        'نسبت ولی',
        opts(['father', 'پدر'], ['mother', 'مادر'], ['guardian', 'سرپرست']),
        { default: 'father' },
      ),
      field('emergency_phone', 'تماس اضطراری', 'tel'),
      field('address', 'نشانی منزل', 'textarea'),
      select(
        'blood_type',
        'گروه خونی',
        opts(
          ['A+', 'A+'],
          ['A-', 'A−'],
          ['B+', 'B+'],
          ['B-', 'B−'],
          ['O+', 'O+'],
          ['O-', 'O−'],
          ['AB+', 'AB+'],
          ['AB-', 'AB−'],
        ),
      ),
      field('medical_notes', 'ملاحظات پزشکی', 'textarea'),
      ref('route_id', 'سرویس مدرسه', 'routes'),
      select(
        'status',
        'وضعیت',
        opts(['active', 'در حال تحصیل'], ['inactive', 'غیرفعال'], ['graduated', 'فارغ‌التحصیل']),
        { default: 'active' },
      ),
    ],
  },
  teachers: {
    module: 'teachers',
    title: 'معلمان',
    singular: 'معلم',
    icon: 'UsersRound',
    read: educators,
    write: ['admin'],
    display: ['first_name', 'last_name'],
    columns: ['first_name', 'specialty', 'phone', 'employment', 'status'],
    fields: [
      field('first_name', 'نام', 'text', required),
      field('last_name', 'نام خانوادگی', 'text', required),
      field('national_id', 'کد ملی', 'text', { pattern: 'national', unique: true }),
      field('specialty', 'تخصص / درس', 'text', required),
      field('phone', 'شماره تماس', 'tel', required),
      field('email', 'ایمیل', 'email'),
      field('qualification', 'مدرک تحصیلی'),
      date('hire_date', 'تاریخ همکاری'),
      select(
        'employment',
        'نوع همکاری',
        opts(['full_time', 'تمام‌وقت'], ['part_time', 'پاره‌وقت'], ['contract', 'قراردادی']),
        { default: 'full_time' },
      ),
      field('bio', 'درباره معلم', 'textarea'),
      select('status', 'وضعیت', opts(['active', 'فعال'], ['inactive', 'غیرفعال']), {
        default: 'active',
      }),
    ],
  },
  classes: {
    module: 'classes',
    title: 'کلاس‌ها',
    singular: 'کلاس',
    icon: 'School',
    read: everyone,
    write: ['admin'],
    display: ['name'],
    columns: ['name', 'grade', 'teacher_id', 'capacity', 'room'],
    fields: [
      field('name', 'نام کلاس', 'text', required),
      select('grade', 'پایه تحصیلی', gradeOptions, { default: '7', required: true }),
      ref('teacher_id', 'معلم راهنما', 'teachers', required),
      num('capacity', 'ظرفیت کلاس', {
        default: 30,
        min: 1,
        max: 60,
        required: true,
        integer: true,
      }),
      field('room', 'شماره اتاق'),
      select('shift', 'نوبت', opts(['morning', 'صبح'], ['afternoon', 'عصر']), {
        default: 'morning',
      }),
      field('description', 'توضیحات', 'textarea'),
    ],
  },
  subjects: {
    module: 'education',
    title: 'دروس',
    singular: 'درس',
    icon: 'BookOpen',
    read: everyone,
    write: ['admin'],
    display: ['name'],
    columns: ['name', 'code', 'grade', 'weekly_hours'],
    fields: [
      field('name', 'عنوان درس', 'text', required),
      field('code', 'کد درس', 'text', { ...required, unique: true }),
      select(
        'grade',
        'پایه',
        opts(['all', 'همه پایه‌ها'], ...gradeOptions.map((o) => [o.value, o.label])),
        { default: 'all' },
      ),
      num('weekly_hours', 'ساعت هفتگی', { default: 2, min: 1, max: 12 }),
      field('description', 'توضیحات', 'textarea'),
    ],
  },
  schedules: {
    module: 'education',
    title: 'برنامه هفتگی',
    singular: 'زنگ درسی',
    icon: 'CalendarRange',
    read: everyone,
    write: ['admin'],
    display: ['title'],
    columns: ['class_id', 'subject_id', 'teacher_id', 'day', 'start_time'],
    fields: [
      field('title', 'عنوان زنگ', 'text', required),
      ref('class_id', 'کلاس', 'classes', required),
      ref('subject_id', 'درس', 'subjects', required),
      ref('teacher_id', 'معلم', 'teachers', required),
      select(
        'day',
        'روز هفته',
        opts(
          ['0', 'شنبه'],
          ['1', 'یکشنبه'],
          ['2', 'دوشنبه'],
          ['3', 'سه‌شنبه'],
          ['4', 'چهارشنبه'],
          ['5', 'پنجشنبه'],
        ),
        { default: '0', required: true },
      ),
      field('start_time', 'ساعت شروع', 'time', required),
      field('end_time', 'ساعت پایان', 'time', required),
      field('room', 'اتاق'),
    ],
  },
  assignments: {
    module: 'education',
    title: 'تکالیف',
    singular: 'تکلیف',
    icon: 'NotebookPen',
    read: everyone,
    write: educators,
    display: ['title'],
    columns: ['title', 'class_id', 'subject_id', 'due_date', 'status'],
    fields: [
      field('title', 'عنوان تکلیف', 'text', required),
      ref('class_id', 'کلاس', 'classes', required),
      ref('subject_id', 'درس', 'subjects', required),
      ref('teacher_id', 'معلم', 'teachers'),
      date('due_date', 'مهلت تحویل', required),
      num('max_score', 'حداکثر نمره', { default: 20, min: 1, max: 100 }),
      field('description', 'شرح تکلیف', 'textarea', required),
      field('file_id', 'فایل تکلیف', 'file'),
      select('status', 'وضعیت', opts(['published', 'منتشرشده'], ['closed', 'پایان‌یافته']), {
        default: 'published',
      }),
    ],
  },
  exams: {
    module: 'education',
    title: 'آزمون‌ها',
    singular: 'آزمون',
    icon: 'ClipboardList',
    read: everyone,
    write: educators,
    display: ['title'],
    columns: ['title', 'class_id', 'subject_id', 'exam_date', 'type'],
    fields: [
      field('title', 'عنوان آزمون', 'text', required),
      ref('class_id', 'کلاس', 'classes', required),
      ref('subject_id', 'درس', 'subjects', required),
      date('exam_date', 'تاریخ آزمون', required),
      field('start_time', 'ساعت', 'time'),
      num('duration', 'مدت (دقیقه)', { default: 60, min: 1, max: 240 }),
      num('max_score', 'حداکثر نمره', { default: 20, min: 1, max: 100 }),
      field('location', 'محل برگزاری'),
      select(
        'type',
        'نوع آزمون',
        opts(['quiz', 'کلاسی'], ['midterm', 'میان‌ترم'], ['final', 'پایان‌ترم']),
        { default: 'quiz' },
      ),
    ],
  },
  grades: {
    module: 'education',
    title: 'نمرات و کارنامه',
    singular: 'نمره',
    icon: 'Award',
    read: everyone,
    write: educators,
    display: ['title'],
    columns: ['student_id', 'subject_id', 'score', 'max_score', 'term'],
    computed: [ref('class_id', 'کلاس هنگام ارزشیابی', 'classes')],
    fields: [
      field('title', 'عنوان ارزشیابی', 'text', required),
      ref('student_id', 'دانش‌آموز', 'students', required),
      ref('subject_id', 'درس', 'subjects', required),
      ref('exam_id', 'آزمون مرتبط', 'exams'),
      num('score', 'نمره', { min: 0, max: 100, required: true }),
      num('max_score', 'نمره کامل', { default: 20, min: 1, max: 100, required: true }),
      num('coefficient', 'ضریب', { default: 1, min: 0.1, max: 10, required: true }),
      field('term', 'نیم‌سال', 'text', { default: 'نیم‌سال اول' }),
      field('notes', 'یادداشت معلم', 'textarea'),
    ],
  },
  announcements: {
    module: 'announcements',
    title: 'اطلاعیه‌ها',
    singular: 'اطلاعیه',
    icon: 'Megaphone',
    read: everyone,
    write: educators,
    display: ['title'],
    columns: ['title', 'audience', 'class_id', 'publish_date'],
    fields: [
      field('title', 'عنوان اطلاعیه', 'text', required),
      field('body', 'متن اطلاعیه', 'textarea', required),
      select(
        'audience',
        'مخاطب',
        opts(
          ['all', 'همه اعضا'],
          ['teacher', 'معلمان'],
          ['student', 'دانش‌آموزان'],
          ['parent', 'اولیا'],
        ),
        { default: 'all', required: true },
      ),
      ref('class_id', 'کلاس (خالی = عمومی)', 'classes'),
      date('publish_date', 'تاریخ انتشار', required),
      date('expires_at', 'پایان نمایش (اختیاری)'),
    ],
  },
  events: {
    module: 'calendar',
    title: 'رویدادها',
    singular: 'رویداد',
    icon: 'CalendarDays',
    read: everyone,
    write: educators,
    display: ['title'],
    columns: ['title', 'start_date', 'type', 'location'],
    fields: [
      field('title', 'عنوان رویداد', 'text', required),
      date('start_date', 'تاریخ شروع', required),
      date('end_date', 'تاریخ پایان'),
      field('start_time', 'ساعت', 'time'),
      select(
        'type',
        'نوع رویداد',
        opts(
          ['meeting', 'جلسه'],
          ['trip', 'اردو'],
          ['exam', 'آزمون'],
          ['celebration', 'مناسبت'],
          ['workshop', 'کارگاه'],
        ),
        { default: 'meeting' },
      ),
      field('location', 'محل برگزاری'),
      ref('class_id', 'کلاس مرتبط', 'classes'),
      field('description', 'توضیحات', 'textarea'),
    ],
  },
  invoices: {
    module: 'finance',
    title: 'شهریه و صورتحساب',
    singular: 'صورتحساب',
    icon: 'ReceiptText',
    read: ['admin', 'student', 'parent'],
    write: ['admin'],
    display: ['title'],
    columns: ['student_id', 'title', 'amount', 'due_date', 'status'],
    fields: [
      field('title', 'عنوان صورتحساب', 'text', required),
      ref('student_id', 'دانش‌آموز', 'students', required),
      num('amount', 'مبلغ (تومان)', { min: 1, required: true }),
      date('due_date', 'سررسید', required),
      field('term', 'دوره', 'text', { default: '۱۴۰۵–۱۴۰۶' }),
      field('notes', 'توضیحات', 'textarea'),
    ],
    computed: [
      select(
        'status',
        'وضعیت',
        opts(['unpaid', 'پرداخت‌نشده'], ['partial', 'پرداخت جزئی'], ['paid', 'تسویه‌شده']),
      ),
      num('paid_amount', 'پرداخت‌شده (تومان)'),
    ],
  },
  payments: {
    module: 'finance',
    title: 'پرداخت‌ها',
    singular: 'پرداخت',
    icon: 'CreditCard',
    read: ['admin', 'student', 'parent'],
    write: ['admin'],
    display: ['reference'],
    columns: ['invoice_id', 'amount', 'payment_date', 'method', 'reference'],
    fields: [
      ref('invoice_id', 'صورتحساب', 'invoices', required),
      num('amount', 'مبلغ (تومان)', { min: 1, required: true }),
      date('payment_date', 'تاریخ پرداخت', required),
      select(
        'method',
        'روش پرداخت',
        opts(['transfer', 'واریز بانکی'], ['cash', 'نقدی'], ['pos', 'کارت‌خوان'], ['cheque', 'چک']),
        { default: 'transfer' },
      ),
      field('reference', 'شماره پیگیری', 'text', { required: true, unique: true }),
      field('notes', 'توضیحات', 'textarea'),
    ],
  },
  expenses: {
    module: 'finance',
    title: 'هزینه‌های مدرسه',
    singular: 'هزینه',
    icon: 'Banknote',
    read: ['admin'],
    write: ['admin'],
    display: ['title'],
    columns: ['title', 'category', 'amount', 'expense_date'],
    fields: [
      field('title', 'شرح هزینه', 'text', required),
      select(
        'category',
        'دسته',
        opts(
          ['utilities', 'قبوض'],
          ['supplies', 'ملزومات'],
          ['maintenance', 'تعمیرات'],
          ['education', 'آموزشی'],
          ['other', 'سایر'],
        ),
        { default: 'supplies' },
      ),
      num('amount', 'مبلغ (تومان)', { min: 1, required: true }),
      date('expense_date', 'تاریخ هزینه', required),
      field('reference', 'شماره سند'),
      field('notes', 'توضیحات', 'textarea'),
    ],
  },
  books: {
    module: 'library',
    title: 'کتاب‌های کتابخانه',
    singular: 'کتاب',
    icon: 'Library',
    read: everyone,
    write: ['admin'],
    display: ['title'],
    columns: ['title', 'author', 'category', 'copies'],
    fields: [
      field('title', 'نام کتاب', 'text', required),
      field('author', 'نویسنده', 'text', required),
      field('isbn', 'شابک', 'text', { unique: true }),
      field('category', 'موضوع', 'text', required),
      num('copies', 'تعداد نسخه', { default: 1, min: 1, integer: true, required: true }),
      field('shelf', 'قفسه'),
      field('description', 'توضیحات', 'textarea'),
    ],
  },
  loans: {
    module: 'library',
    title: 'امانت کتاب',
    singular: 'امانت',
    icon: 'BookCopy',
    read: everyone,
    write: ['admin'],
    display: ['title'],
    columns: ['book_id', 'student_id', 'borrow_date', 'due_date', 'return_date'],
    fields: [
      ref('book_id', 'کتاب', 'books', required),
      ref('student_id', 'دانش‌آموز', 'students', required),
      date('borrow_date', 'تاریخ امانت', required),
      date('due_date', 'مهلت بازگشت', required),
      date('return_date', 'تاریخ بازگشت'),
      field('notes', 'یادداشت', 'textarea'),
    ],
  },
  inventory: {
    module: 'services',
    title: 'تجهیزات و اموال',
    singular: 'تجهیز',
    icon: 'Boxes',
    read: ['admin'],
    write: ['admin'],
    display: ['name'],
    columns: ['name', 'category', 'quantity', 'location', 'condition'],
    fields: [
      field('name', 'نام تجهیز', 'text', required),
      field('category', 'دسته', 'text', required),
      num('quantity', 'تعداد', { default: 1, min: 0, integer: true, required: true }),
      field('location', 'محل نگهداری'),
      field('serial_no', 'شماره اموال', 'text', { unique: true }),
      select(
        'condition',
        'وضعیت',
        opts(['good', 'سالم'], ['repair', 'نیازمند تعمیر'], ['retired', 'اسقاط']),
        { default: 'good' },
      ),
      field('notes', 'توضیحات', 'textarea'),
    ],
  },
  routes: {
    module: 'services',
    title: 'سرویس مدرسه',
    singular: 'سرویس',
    icon: 'Bus',
    read: everyone,
    write: ['admin'],
    display: ['name'],
    columns: ['name', 'driver_name', 'phone', 'plate', 'capacity'],
    fields: [
      field('name', 'نام مسیر', 'text', required),
      field('driver_name', 'نام راننده', 'text', required),
      field('phone', 'تماس راننده', 'tel', required),
      field('plate', 'پلاک خودرو', 'text', required),
      num('capacity', 'ظرفیت', { default: 20, min: 1, max: 60, integer: true }),
      num('fee', 'هزینه ماهانه (تومان)'),
      field('stops', 'ایستگاه‌ها', 'textarea'),
    ],
  },
  counseling: {
    module: 'students',
    title: 'مشاوره',
    singular: 'جلسه مشاوره',
    icon: 'HeartHandshake',
    read: educators,
    write: educators,
    display: ['title'],
    columns: ['student_id', 'title', 'counselor', 'session_date', 'status'],
    fields: [
      ref('student_id', 'دانش‌آموز', 'students', required),
      field('title', 'موضوع جلسه', 'text', required),
      field('counselor', 'نام مشاور', 'text', required),
      date('session_date', 'تاریخ جلسه', required),
      field('notes', 'یادداشت محرمانه', 'textarea'),
      field('follow_up', 'اقدام بعدی', 'textarea'),
      select(
        'status',
        'وضعیت',
        opts(
          ['planned', 'برنامه‌ریزی‌شده'],
          ['completed', 'انجام‌شده'],
          ['follow_up', 'نیازمند پیگیری'],
        ),
        { default: 'planned' },
      ),
    ],
  },
  discipline: {
    module: 'students',
    title: 'سوابق رفتاری',
    singular: 'سابقه رفتاری',
    icon: 'BadgeCheck',
    read: everyone,
    write: educators,
    display: ['title'],
    columns: ['student_id', 'title', 'record_date', 'type'],
    fields: [
      ref('student_id', 'دانش‌آموز', 'students', required),
      field('title', 'شرح سابقه', 'text', required),
      date('record_date', 'تاریخ', required),
      select(
        'type',
        'نوع',
        opts(['positive', 'تشویق'], ['warning', 'تذکر'], ['incident', 'رخداد']),
        { default: 'positive' },
      ),
      field('action', 'اقدام / نتیجه', 'textarea'),
    ],
  },
  health: {
    module: 'students',
    title: 'پرونده سلامت',
    singular: 'معاینه',
    icon: 'HeartPulse',
    read: ['admin', 'student', 'parent'],
    write: ['admin'],
    display: ['title'],
    columns: ['student_id', 'title', 'check_date', 'type'],
    fields: [
      ref('student_id', 'دانش‌آموز', 'students', required),
      field('title', 'عنوان معاینه', 'text', required),
      date('check_date', 'تاریخ', required),
      select(
        'type',
        'نوع',
        opts(
          ['checkup', 'معاینه عمومی'],
          ['vaccine', 'واکسیناسیون'],
          ['vision', 'بینایی'],
          ['other', 'سایر'],
        ),
        { default: 'checkup' },
      ),
      field('description', 'نتیجه معاینه', 'textarea'),
      field('recommendation', 'توصیه پزشکی', 'textarea'),
    ],
  },
  documents: {
    module: 'students',
    title: 'مدارک دانش‌آموز',
    singular: 'مدرک',
    icon: 'FolderOpen',
    read: everyone,
    write: ['admin', 'student', 'parent'],
    display: ['title'],
    columns: ['student_id', 'title', 'type', 'expires_at'],
    fields: [
      ref('student_id', 'دانش‌آموز', 'students', required),
      field('title', 'عنوان مدرک', 'text', required),
      select(
        'type',
        'نوع مدرک',
        opts(
          ['identity', 'هویتی'],
          ['educational', 'تحصیلی'],
          ['medical', 'پزشکی'],
          ['other', 'سایر'],
        ),
        { default: 'identity' },
      ),
      field('file_id', 'فایل مدرک', 'file', required),
      date('expires_at', 'تاریخ اعتبار'),
      field('notes', 'توضیحات', 'textarea'),
    ],
  },
  payroll: {
    module: 'teachers',
    title: 'حقوق همکاران',
    singular: 'فیش حقوقی',
    icon: 'HandCoins',
    read: educators,
    write: ['admin'],
    display: ['month'],
    columns: ['teacher_id', 'month', 'gross', 'deductions', 'status'],
    fields: [
      ref('teacher_id', 'معلم', 'teachers', required),
      field('month', 'ماه / سال', 'text', required),
      num('gross', 'حقوق ناخالص (تومان)', { min: 1, required: true }),
      num('deductions', 'کسورات (تومان)', { default: 0 }),
      date('payment_date', 'تاریخ پرداخت'),
      select('status', 'وضعیت', opts(['pending', 'در انتظار پرداخت'], ['paid', 'پرداخت‌شده']), {
        default: 'pending',
      }),
      field('notes', 'توضیحات', 'textarea'),
    ],
  },
  visitors: {
    module: 'services',
    title: 'دفتر ورود مهمانان',
    singular: 'مراجعه',
    icon: 'ContactRound',
    read: ['admin'],
    write: ['admin'],
    display: ['full_name'],
    columns: ['full_name', 'purpose', 'host', 'visit_date', 'entry_time'],
    fields: [
      field('full_name', 'نام مراجعه‌کننده', 'text', required),
      field('phone', 'شماره تماس', 'tel'),
      field('purpose', 'علت مراجعه', 'text', required),
      field('host', 'میزبان', 'text', required),
      date('visit_date', 'تاریخ مراجعه', required),
      field('entry_time', 'ساعت ورود', 'time', required),
      field('exit_time', 'ساعت خروج', 'time'),
      field('notes', 'یادداشت', 'textarea'),
    ],
  },
  terms: {
    module: 'settings',
    title: 'سال‌های تحصیلی',
    singular: 'سال تحصیلی',
    icon: 'CalendarRange',
    read: ['admin'],
    write: ['admin'],
    display: ['name'],
    columns: ['name', 'start_date', 'end_date', 'status'],
    fields: [
      field('name', 'نام سال تحصیلی', 'text', required),
      date('start_date', 'شروع', required),
      date('end_date', 'پایان', required),
      select(
        'status',
        'وضعیت',
        opts(['current', 'سال جاری'], ['archived', 'بایگانی'], ['planned', 'آینده']),
        { default: 'planned' },
      ),
    ],
  },
  rooms: {
    module: 'classes',
    title: 'فضاهای آموزشی',
    singular: 'فضا',
    icon: 'Building2',
    read: educators,
    write: ['admin'],
    display: ['name'],
    columns: ['name', 'type', 'capacity', 'building'],
    fields: [
      field('name', 'نام / شماره اتاق', 'text', required),
      select(
        'type',
        'نوع فضا',
        opts(
          ['classroom', 'کلاس درس'],
          ['lab', 'آزمایشگاه'],
          ['workshop', 'کارگاه'],
          ['hall', 'سالن'],
        ),
        { default: 'classroom' },
      ),
      num('capacity', 'ظرفیت', { default: 30, min: 1, integer: true }),
      field('building', 'ساختمان / طبقه'),
      field('equipment', 'تجهیزات', 'textarea'),
    ],
  },
};
const actions = [
  ['view', 'مشاهده و جست‌وجوی'],
  ['create', 'ثبت'],
  ['edit', 'ویرایش'],
  ['delete', 'حذف ایمن'],
];
export const featureDefs = Object.entries(resourceDefs).flatMap(([key, def]) =>
  actions.map(([action, title]) => ({
    id: `${key}.${action}`,
    module: def.module,
    name: `${title} ${action === 'view' ? def.title : def.singular}`,
    resource: key,
    action,
    roles: action === 'view' ? def.read : def.write,
    requires: action === 'view' ? [] : [`${key}.view`],
  })),
);
const extraFeatures = [
  ['dashboard.view', 'dashboard', 'نمای کلی نقش‌محور مدرسه'],
  ['dashboard.statistics', 'dashboard', 'کارت‌های آماری زنده'],
  ['dashboard.chart', 'dashboard', 'نمودار روند حضور'],
  ['dashboard.activities', 'dashboard', 'فعالیت‌های اخیر مدرسه'],
  ['students.profile', 'students', 'پرونده یکپارچه دانش‌آموز و اولیا'],
  ['students.export', 'students', 'خروجی CSV دانش‌آموزان'],
  ['students.import', 'students', 'ورود گروهی دانش‌آموز از CSV'],
  ['students.account', 'students', 'ساخت حساب کاربری دانش‌آموز'],
  ['teachers.account', 'teachers', 'ساخت حساب کاربری معلم'],
  ['classes.roster', 'classes', 'فهرست اعضای کلاس'],
  ['attendance.view', 'attendance', 'فهرست روزانه حضور و غیاب'],
  ['attendance.record', 'attendance', 'ثبت حاضر، غایب، تأخیر و موجه'],
  ['attendance.bulk', 'attendance', 'ثبت گروهی حضور کلاس'],
  ['attendance.export', 'attendance', 'خروجی حضور و غیاب'],
  ['attendance.history', 'attendance', 'تاریخچه حضور دانش‌آموز'],
  ['tickets.view', 'tickets', 'صندوق تیکت با دسترسی اختصاصی'],
  ['tickets.create', 'tickets', 'ارسال تیکت به مدیر یا معلم'],
  ['tickets.reply', 'tickets', 'پاسخ در گفت‌وگوی تیکت'],
  ['tickets.manage', 'tickets', 'تغییر وضعیت و اولویت تیکت'],
  ['tickets.attachments', 'tickets', 'پیوست امن فایل در تیکت'],
  ['assignments.submit', 'education', 'تحویل تکلیف توسط دانش‌آموز'],
  ['assignments.review', 'education', 'ارزیابی و بازخورد تکالیف'],
  ['reports.view', 'reports', 'گزارش‌های تجمیعی و معدل وزنی'],
  ['reports.export', 'reports', 'دانلود گزارش قابل استفاده در اکسل'],
  ['notifications.view', 'notifications', 'اعلان‌های شخصی'],
  ['notifications.read', 'notifications', 'ثبت اعلان به عنوان خوانده‌شده'],
  ['profile.edit', 'profile', 'ویرایش نام و تماس حساب'],
  ['profile.password', 'profile', 'تغییر رمز عبور با بررسی رمز فعلی'],
  ['settings.school', 'settings', 'مشخصات و اطلاعات تماس مدرسه'],
  ['settings.modules', 'settings', 'فعال‌سازی ماژول و قابلیت', true],
  ['settings.accounts', 'settings', 'مدیریت وضعیت حساب‌های کاربری'],
  ['settings.reset_password', 'settings', 'بازنشانی امن رمز کاربران'],
  ['settings.backup', 'settings', 'پشتیبان قابل دانلود SQLite'],
  ['settings.audit', 'settings', 'گزارش رویدادهای مدیریتی'],
];
featureDefs.push(
  ...extraFeatures.map(([id, module, name, locked]) => ({ id, module, name, locked: !!locked })),
);
// Explicit dependencies prevent alternate endpoints bypassing a disabled read capability.
const dependencies = {
  'dashboard.statistics': ['dashboard.view'],
  'dashboard.chart': ['dashboard.view', 'attendance.view'],
  'dashboard.activities': ['dashboard.view'],
  'students.profile': ['students.view'],
  'students.export': ['students.view'],
  'students.import': ['students.view', 'students.create'],
  'students.account': ['students.view'],
  'teachers.account': ['teachers.view'],
  'classes.roster': ['classes.view', 'students.view'],
  'attendance.record': ['attendance.view'],
  'attendance.bulk': ['attendance.record'],
  'attendance.export': ['attendance.view'],
  'attendance.history': ['attendance.view'],
  'tickets.create': ['tickets.view'],
  'tickets.reply': ['tickets.view'],
  'tickets.manage': ['tickets.view'],
  'tickets.attachments': ['tickets.view'],
  'assignments.submit': ['assignments.view'],
  'assignments.review': ['assignments.view'],
  'reports.export': ['reports.view'],
  'notifications.read': ['notifications.view'],
  'settings.reset_password': ['settings.accounts'],
};
for (const feature of featureDefs) {
  feature.requires ||= dependencies[feature.id] || [];
  feature.roles ||=
    feature.id.startsWith('settings.') ||
    ['students.import', 'students.account', 'teachers.account'].includes(feature.id)
      ? ['admin']
      : ['attendance.record', 'attendance.bulk', 'assignments.review'].includes(feature.id)
        ? educators
        : feature.id === 'assignments.submit'
          ? ['student']
          : everyone;
}
export function featureAvailable(config, role, id) {
  const feature = config?.features.find((item) => item.id === id);
  return (
    !!feature?.enabled &&
    feature.roles.includes(role) &&
    !!config.modules.find((module) => module.id === feature.module)?.enabled &&
    feature.requires.every((dependency) => featureAvailable(config, role, dependency))
  );
}
export const moduleGroups = {
  students: ['students', 'documents', 'discipline', 'health', 'counseling'],
  teachers: ['teachers', 'payroll'],
  classes: ['classes', 'rooms'],
  education: ['subjects', 'schedules', 'assignments', 'exams', 'grades'],
  announcements: ['announcements'],
  calendar: ['events'],
  finance: ['invoices', 'payments', 'expenses'],
  library: ['books', 'loans'],
  services: ['routes', 'inventory', 'visitors'],
  settings: ['terms'],
};
export const resourceLabel = (resource, row) => {
  if (!row) return '—';
  const def = resourceDefs[resource];
  return (
    def?.display
      .map((key) => row[key])
      .filter(Boolean)
      .join(' ') ||
    row.title ||
    `#${row.id}`
  );
};
